### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by jewelsjacobs** [JSteunou/marionetteify#1]
It would be cool to  add e2e and unit tests to this and the grunt pipeline!

**Comment by JSteunou** [comment]
It would and I'm open to PR. I have no time to improve this example. I'll try to republish a thing with this summer.

**Comment by jewelsjacobs** [comment]
I managed to get the test runner working in the build pipeline, but the tests I wrote are not working.  Hopefully I can submit a PR soon.
